<?php

use Drupal\Component\Utility\SafeMarkup;
use Drupal\views\ViewExecutable;
use Drupal\mollom\Entity\FormInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_page_attachments().
 */
function limograde_quote_page_attachments(array &$attachments) {
  if (!\Drupal::currentUser()->hasPermission('access content')) {
    return;
  }
  $attachments['#attached']['library'][] = 'limograde_quote/js_cookie';
  $attachments['#attached']['library'][] = 'limograde_quote/quote_js';
}

/**
 * Implements hook_mail().
 */
function limograde_quote_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );
  switch ($key) {
    case 'quote':
      $from = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('E-mail sent from @site-name', array('@site-name' => $from), $options);
      $account = \Drupal::currentUser();
      $message['body'][] = t('@name sent you the following message:', array('@name' => $account->getUsername()), $options);
      $message['body'][] = SafeMarkup::checkPlain($params['message']);
      break;
  }
}

/**
 * Implements hook_mail_alter().
 */
function limograde_quote_mail_alter(&$message) {
  $options = array(
    'langcode' => $message['langcode'],
  );
  $signature = t("\n--\nMail altered by limograde_quote module.", array(), $options);
  if (is_array($message['body'])) {
    $message['body'][] = $signature;
  }
  else {
    // Some modules erroneously use a string.
    $message['body'] .= $signature;
  }
}

/**
 * Implements hook_mollom_form_list().
 */
function limograde_quote_mollom_form_list() {
  $forms['quote'] = array(
    'title' => t('Quote form'),
    'mode' => FormInterface::MOLLOM_MODE_CAPTCHA,
  );
  return $forms;
}

/**
 * Implements hook_mollom_form_info().
 */
function limograde_quote_mollom_form_info($form_id) {
  switch ($form_id) {
    case 'quote':
      $form_info = array(
        'bypass access' => array('bypass mollom protection'),
      );
      return $form_info;
  }
}

/**
 * Implements hook_form_alter().
 */
function limograde_quote_form_alter(&$form, $form_state, $form_id) {
  if ($form_id === 'quote') {
    $form['submit']['#weight'] = 100;
  }
}
